import os
import subprocess

problems = [
    # Linked List
    {"folder": "Linked_List", "filename": "01_reverse_linked_list.py", "title": "Reverse Linked List", "code": 'class Solution:\n    def reverseList(self, head):\n        prev, curr = None, head\n        while curr:\n            nxt = curr.next\n            curr.next = prev\n            prev = curr\n            curr = nxt\n        return prev\n'},
    {"folder": "Linked_List", "filename": "02_merge_two_sorted_lists.py", "title": "Merge Two Sorted Lists", "code": 'class ListNode:\n    def __init__(self, val=0, next=None): self.val = val; self.next = next\nclass Solution:\n    def mergeTwoLists(self, list1, list2):\n        dummy = ListNode()\n        tail = dummy\n        while list1 and list2:\n            if list1.val < list2.val:\n                tail.next = list1\n                list1 = list1.next\n            else:\n                tail.next = list2\n                list2 = list2.next\n            tail = tail.next\n        if list1:\n            tail.next = list1\n        elif list2:\n            tail.next = list2\n        return dummy.next\n'},
    {"folder": "Linked_List", "filename": "03_reorder_list.py", "title": "Reorder List", "code": 'class Solution:\n    def reorderList(self, head) -> None:\n        slow, fast = head, head.next\n        while fast and fast.next:\n            slow = slow.next\n            fast = fast.next.next\n        second = slow.next\n        slow.next = None\n        prev = None\n        while second:\n            tmp = second.next\n            second.next = prev\n            prev = second\n            second = tmp\n        first, second = head, prev\n        while second:\n            tmp1, tmp2 = first.next, second.next\n            first.next = second\n            second.next = tmp1\n            first = tmp1\n            second = tmp2\n'},
    {"folder": "Linked_List", "filename": "04_remove_nth_node_from_end_of_list.py", "title": "Remove Nth Node From End of List", "code": 'class ListNode:\n    def __init__(self, val=0, next=None): self.val = val; self.next = next\nclass Solution:\n    def removeNthFromEnd(self, head, n: int):\n        dummy = ListNode(0, head)\n        left = dummy\n        right = head\n        while n > 0:\n            right = right.next\n            n -= 1\n        while right:\n            left = left.next\n            right = right.next\n        left.next = left.next.next\n        return dummy.next\n'},
    {"folder": "Linked_List", "filename": "05_copy_list_with_random_pointer.py", "title": "Copy List with Random Pointer", "code": 'class Node:\n    def __init__(self, x: int, next=None, random=None): self.val = int(x); self.next = next; self.random = random\nclass Solution:\n    def copyRandomList(self, head):\n        oldToCopy = {None: None}\n        cur = head\n        while cur:\n            oldToCopy[cur] = Node(cur.val)\n            cur = cur.next\n        cur = head\n        while cur:\n            copy = oldToCopy[cur]\n            copy.next = oldToCopy[cur.next]\n            copy.random = oldToCopy[cur.random]\n            cur = cur.next\n        return oldToCopy[head]\n'},
    {"folder": "Linked_List", "filename": "06_add_two_numbers.py", "title": "Add Two Numbers", "code": 'class ListNode:\n    def __init__(self, val=0, next=None): self.val = val; self.next = next\nclass Solution:\n    def addTwoNumbers(self, l1, l2):\n        dummy = ListNode()\n        cur = dummy\n        carry = 0\n        while l1 or l2 or carry:\n            v1 = l1.val if l1 else 0\n            v2 = l2.val if l2 else 0\n            val = v1 + v2 + carry\n            carry = val // 10\n            val = val % 10\n            cur.next = ListNode(val)\n            cur = cur.next\n            l1 = l1.next if l1 else None\n            l2 = l2.next if l2 else None\n        return dummy.next\n'},
    {"folder": "Linked_List", "filename": "07_linked_list_cycle.py", "title": "Linked List Cycle", "code": 'class Solution:\n    def hasCycle(self, head) -> bool:\n        slow, fast = head, head\n        while fast and fast.next:\n            slow = slow.next\n            fast = fast.next.next\n            if slow == fast:\n                return True\n        return False\n'},
    {"folder": "Linked_List", "filename": "08_find_the_duplicate_number.py", "title": "Find the Duplicate Number", "code": 'class Solution:\n    def findDuplicate(self, nums: list[int]) -> int:\n        slow, fast = 0, 0\n        while True:\n            slow = nums[slow]\n            fast = nums[nums[fast]]\n            if slow == fast:\n                break\n        slow2 = 0\n        while True:\n            slow = nums[slow]\n            slow2 = nums[slow2]\n            if slow == slow2:\n                return slow\n'},
    {"folder": "Linked_List", "filename": "09_lru_cache.py", "title": "LRU Cache", "code": 'class Node:\n    def __init__(self, key, val):\n        self.key, self.val = key, val\n        self.prev = self.next = None\nclass LRUCache:\n    def __init__(self, capacity: int):\n        self.cap = capacity\n        self.cache = {}\n        self.left, self.right = Node(0, 0), Node(0, 0)\n        self.left.next, self.right.prev = self.right, self.left\n    def remove(self, node):\n        prev, nxt = node.prev, node.next\n        prev.next, nxt.prev = nxt, prev\n    def insert(self, node):\n        prev, nxt = self.right.prev, self.right\n        prev.next = nxt.prev = node\n        node.next, node.prev = nxt, prev\n    def get(self, key: int) -> int:\n        if key in self.cache:\n            self.remove(self.cache[key])\n            self.insert(self.cache[key])\n            return self.cache[key].val\n        return -1\n    def put(self, key: int, value: int) -> None:\n        if key in self.cache:\n            self.remove(self.cache[key])\n        self.cache[key] = Node(key, value)\n        self.insert(self.cache[key])\n        if len(self.cache) > self.cap:\n            lru = self.left.next\n            self.remove(lru)\n            del self.cache[lru.key]\n'},
    {"folder": "Linked_List", "filename": "10_merge_k_sorted_lists.py", "title": "Merge k Sorted Lists", "code": 'class ListNode:\n    def __init__(self, val=0, next=None): self.val = val; self.next = next\nclass Solution:\n    def mergeKLists(self, lists):\n        if not lists or len(lists) == 0:\n            return None\n        while len(lists) > 1:\n            mergedLists = []\n            for i in range(0, len(lists), 2):\n                l1 = lists[i]\n                l2 = lists[i + 1] if (i + 1) < len(lists) else None\n                mergedLists.append(self.mergeList(l1, l2))\n            lists = mergedLists\n        return lists[0]\n    def mergeList(self, l1, l2):\n        dummy = ListNode()\n        tail = dummy\n        while l1 and l2:\n            if l1.val < l2.val:\n                tail.next = l1\n                l1 = l1.next\n            else:\n                tail.next = l2\n                l2 = l2.next\n            tail = tail.next\n        if l1:\n            tail.next = l1\n        if l2:\n            tail.next = l2\n        return dummy.next\n'},
    {"folder": "Linked_List", "filename": "11_reverse_nodes_in_k_group.py", "title": "Reverse Nodes in k-Group", "code": 'class ListNode:\n    def __init__(self, val=0, next=None): self.val = val; self.next = next\nclass Solution:\n    def reverseKGroup(self, head, k: int):\n        dummy = ListNode(0, head)\n        groupPrev = dummy\n        while True:\n            kth = self.getKth(groupPrev, k)\n            if not kth:\n                break\n            groupNext = kth.next\n            prev, curr = kth.next, groupPrev.next\n            while curr != groupNext:\n                tmp = curr.next\n                curr.next = prev\n                prev = curr\n                curr = tmp\n            tmp = groupPrev.next\n            groupPrev.next = kth\n            groupPrev = tmp\n        return dummy.next\n    def getKth(self, curr, k):\n        while curr and k > 0:\n            curr = curr.next\n            k -= 1\n        return curr\n'},
    # Trees
    {"folder": "Trees", "filename": "01_invert_binary_tree.py", "title": "Invert Binary Tree", "code": 'class Solution:\n    def invertTree(self, root):\n        if not root:\n            return None\n        tmp = root.left\n        root.left = root.right\n        root.right = tmp\n        self.invertTree(root.left)\n        self.invertTree(root.right)\n        return root\n'},
    {"folder": "Trees", "filename": "02_maximum_depth_of_binary_tree.py", "title": "Maximum Depth of Binary Tree", "code": 'class Solution:\n    def maxDepth(self, root) -> int:\n        if not root:\n            return 0\n        return 1 + max(self.maxDepth(root.left), self.maxDepth(root.right))\n'},
    {"folder": "Trees", "filename": "03_diameter_of_binary_tree.py", "title": "Diameter of Binary Tree", "code": 'class Solution:\n    def diameterOfBinaryTree(self, root) -> int:\n        res = 0\n        def dfs(root):\n            nonlocal res\n            if not root:\n                return 0\n            left = dfs(root.left)\n            right = dfs(root.right)\n            res = max(res, left + right)\n            return 1 + max(left, right)\n        dfs(root)\n        return res\n'},
    {"folder": "Trees", "filename": "04_balanced_binary_tree.py", "title": "Balanced Binary Tree", "code": 'class Solution:\n    def isBalanced(self, root) -> bool:\n        def dfs(root):\n            if not root:\n                return [True, 0]\n            left, right = dfs(root.left), dfs(root.right)\n            balanced = left[0] and right[0] and abs(left[1] - right[1]) <= 1\n            return [balanced, 1 + max(left[1], right[1])]\n        return dfs(root)[0]\n'},
    {"folder": "Trees", "filename": "05_same_tree.py", "title": "Same Tree", "code": 'class Solution:\n    def isSameTree(self, p, q) -> bool:\n        if not p and not q:\n            return True\n        if not p or not q or p.val != q.val:\n            return False\n        return self.isSameTree(p.left, q.left) and self.isSameTree(p.right, q.right)\n'},
    {"folder": "Trees", "filename": "06_subtree_of_another_tree.py", "title": "Subtree of Another Tree", "code": 'class Solution:\n    def isSubtree(self, s, t) -> bool:\n        if not t:\n            return True\n        if not s:\n            return False\n        if self.sameTree(s, t):\n            return True\n        return self.isSubtree(s.left, t) or self.isSubtree(s.right, t)\n    def sameTree(self, s, t):\n        if not s and not t:\n            return True\n        if s and t and s.val == t.val:\n            return self.sameTree(s.left, t.left) and self.sameTree(s.right, t.right)\n        return False\n'},
    {"folder": "Trees", "filename": "07_lowest_common_ancestor_of_a_binary_search_tree.py", "title": "Lowest Common Ancestor of a BST", "code": 'class Solution:\n    def lowestCommonAncestor(self, root, p, q):\n        while root:\n            if p.val > root.val and q.val > root.val:\n                root = root.right\n            elif p.val < root.val and q.val < root.val:\n                root = root.left\n            else:\n                return root\n'},
    {"folder": "Trees", "filename": "08_binary_tree_level_order_traversal.py", "title": "Binary Tree Level Order Traversal", "code": 'import collections\nclass Solution:\n    def levelOrder(self, root):\n        res = []\n        q = collections.deque()\n        if root:\n            q.append(root)\n        while q:\n            val = []\n            for i in range(len(q)):\n                node = q.popleft()\n                val.append(node.val)\n                if node.left:\n                    q.append(node.left)\n                if node.right:\n                    q.append(node.right)\n            res.append(val)\n        return res\n'},
    {"folder": "Trees", "filename": "09_binary_tree_right_side_view.py", "title": "Binary Tree Right Side View", "code": 'import collections\nclass Solution:\n    def rightSideView(self, root):\n        res = []\n        q = collections.deque([root] if root else [])\n        while q:\n            rightSide = None\n            for i in range(len(q)):\n                node = q.popleft()\n                if node:\n                    rightSide = node\n                    q.append(node.left)\n                    q.append(node.right)\n            if rightSide:\n                res.append(rightSide.val)\n        return res\n'},
    {"folder": "Trees", "filename": "10_count_good_nodes_in_binary_tree.py", "title": "Count Good Nodes in Binary Tree", "code": 'class Solution:\n    def goodNodes(self, root) -> int:\n        def dfs(node, maxVal):\n            if not node:\n                return 0\n            res = 1 if node.val >= maxVal else 0\n            maxVal = max(maxVal, node.val)\n            res += dfs(node.left, maxVal)\n            res += dfs(node.right, maxVal)\n            return res\n        return dfs(root, root.val)\n'},
    {"folder": "Trees", "filename": "11_validate_binary_search_tree.py", "title": "Validate Binary Search Tree", "code": 'class Solution:\n    def isValidBST(self, root) -> bool:\n        def valid(node, left, right):\n            if not node:\n                return True\n            if not (node.val < right and node.val > left):\n                return False\n            return valid(node.left, left, node.val) and valid(node.right, node.val, right)\n        return valid(root, float("-inf"), float("inf"))\n'}
]

def run_git(args):
    subprocess.run(["git"] + args, check=True)

for p in problems:
    filepath = os.path.join(p["folder"], p["filename"])
    with open(filepath, "w") as f:
        f.write(p["code"])
    with open("progress.md", "a") as f:
        f.write(f"| 2026-06-06 | {p['folder']} | {p['title']} | Complete |\\n")
    run_git(["add", filepath])
    run_git(["add", "progress.md"])
    run_git(["commit", "-m", f"Solve {p['title']}"])

run_git(["push", "-u", "origin", "main"])
